export const PLACEHOLDER_CATEGORIES = ["user", "guild", "channel", "text", "math", "embed", "misc"];

export const PLACEHOLDERS = [
  { key: "user.name", category: "user", type: "variable", descKey: "userName", syntax: "{user.name}", output: "Ada" },
  { key: "user.id", category: "user", type: "variable", descKey: "userId", syntax: "{user.id}", output: "931037124336164957" },
  { key: "user.mention", category: "user", type: "variable", descKey: "userMention", syntax: "{user.mention}", output: "@Ada" },
  { key: "user.discriminator", category: "user", type: "variable", descKey: "userDiscriminator", syntax: "{user.discriminator}", output: "0" },
  { key: "user.avatar", category: "user", type: "variable", descKey: "userAvatar", syntax: "{user.avatar}", output: "https://cdn.discordapp.com/avatars/..." },
  { key: "user.tag", category: "user", type: "variable", descKey: "userTag", syntax: "{user.tag}", output: "Ada#0" },
  { key: "guild.name", category: "guild", type: "variable", descKey: "guildName", syntax: "{guild.name}", output: "Ada's Workshop" },
  { key: "guild.id", category: "guild", type: "variable", descKey: "guildId", syntax: "{guild.id}", output: "1449864932731392223" },
  { key: "guild.members", category: "guild", type: "variable", descKey: "guildMembers", syntax: "{guild.members}", output: "1,204" },
  { key: "guild.icon", category: "guild", type: "variable", descKey: "guildIcon", syntax: "{guild.icon}", output: "https://cdn.discordapp.com/icons/..." },
  { key: "channel.name", category: "channel", type: "variable", descKey: "channelName", syntax: "{channel.name}", output: "general" },
  { key: "channel.id", category: "channel", type: "variable", descKey: "channelId", syntax: "{channel.id}", output: "1449864932731392230" },
  { key: "channel.mention", category: "channel", type: "variable", descKey: "channelMention", syntax: "{channel.mention}", output: "#general" },
  { key: "upper", category: "text", type: "function", args: ["text"], descKey: "upper", syntax: "{upper:hello}", output: "HELLO" },
  { key: "lower", category: "text", type: "function", args: ["text"], descKey: "lower", syntax: "{lower:HELLO}", output: "hello" },
  { key: "title", category: "text", type: "function", args: ["text"], descKey: "title", syntax: "{title:hello world}", output: "Hello World" },
  { key: "length", category: "text", type: "function", args: ["text"], descKey: "length", syntax: "{length:hello}", output: "5" },
  { key: "repeat", category: "text", type: "function", args: ["text", "times"], descKey: "repeat", syntax: "{repeat:hi;3}", output: "hihihi" },
  { key: "sum", category: "math", type: "function", args: ["...values"], descKey: "sum", syntax: "{sum:1;2;3}", output: "6" },
  { key: "sub", category: "math", type: "function", args: ["a", "b"], descKey: "sub", syntax: "{sub:10;3}", output: "7" },
  { key: "mul", category: "math", type: "function", args: ["a", "b"], descKey: "mul", syntax: "{mul:5;3}", output: "15" },
  { key: "div", category: "math", type: "function", args: ["a", "b"], descKey: "div", syntax: "{div:10;2}", output: "5" },
  { key: "embed.title", category: "embed", type: "function", args: ["title"], descKey: "embedTitle", syntax: "{embed.title:Welcome!}" },
  { key: "embed.description", category: "embed", type: "function", args: ["description"], descKey: "embedDescription", syntax: "{embed.description:Enjoy your stay.}" },
  { key: "embed.color", category: "embed", type: "function", args: ["hex"], descKey: "embedColor", syntax: "{embed.color:23a55a}" },
  { key: "embed.footer", category: "embed", type: "function", args: ["text"], descKey: "embedFooter", syntax: "{embed.footer:Powered by Hawk}" },
  { key: "embed.image", category: "embed", type: "function", args: ["url"], descKey: "embedImage", syntax: "{embed.image:https://...}" },
  { key: "embed.thumbnail", category: "embed", type: "function", args: ["url"], descKey: "embedThumbnail", syntax: "{embed.thumbnail:{user.avatar}}" },
  { key: "embed.field", category: "embed", type: "function", args: ["name", "value", "inline"], descKey: "embedField", syntax: "{embed.field:Rank;#4;true}" },
  { key: "emoji", category: "misc", type: "function", args: ["emoji"], descKey: "emoji", syntax: "{emoji:🎉}" },
  { key: "if", category: "misc", type: "function", args: ["condition", "true_val", "false_val"], descKey: "if", syntax: "{if:1;Welcome back!;Welcome!}", output: "Welcome back!" },
];